### PR TITLE
feat(legacy-preset-chart-nvd3): show negative values on bars

### PR DESCRIPTION
**Pull request by betodealmeida**
🐛 Bug Fix

Turns out the functionality to show values in bars only works when they're positive. I modified the code so that it works with negative values as well:

screen shot 2019-03-05 at 12 38 27 am

This PR is based on https://github.com/apache-superset/superset-ui-plugins/pull/7.

### CODE REVIEW

**Comment by kristw** [comment]
This seems to combine changes from another PR as well.

**Comment by betodealmeida** [comment]
@kristw yeah, I branched this one off of that one.

**Comment by kristw** [comment]
Do you want to complete that one first? This one can't be merged until that one goes in.

**Comment by betodealmeida** [comment]
Ah, sorry for getting the title wrong.

I fixed the other one so it doesn't create a bunch of `g`s

**Review by kristw — APPROVED** [review]

**Pull request merged**
