### PR TITLE
fix: ignore disabled series in stacked bar values

### PR DESCRIPTION
**Pull request by etr2460**
🐛 Bug Fix
Sets the bar values to the sum of only enabled series. This means that when you click on the legend to enable/disable series in multibar charts, the bar value will be the sum of only the visible bars. Unable to test right now because the build is broken, but will include screenshots once I can.

See sums changing when series are disabled:
Screen Shot 2019-06-06 at 3 48 44 PM
Screen Shot 2019-06-06 at 3 48 58 PM

to: @kristw

### CODE REVIEW

**Comment by kristw** [comment]
Master is back! Build not broken anymore. Please rebase and push again.

**Comment by etr2460** [comment]
I'm also removing some of the test data for nvd3 bar charts since they weren't formatting very well in storybook

**Comment by etr2460** [comment]
@kristw this should be good for review now

**Review by kristw — APPROVED** [review]

**Comment by etr2460** [comment]
I'll need you to merge it too since I don't have write access

**Comment by conglei** [comment]
The build failed :(

**Comment by etr2460** [comment]
They weren’t due to changes in anything I touched though, were they? It looked like lint errors in other files

**Comment by kristw** [comment]
Minor linting. I will take a look when i can

**Comment by kristw** [comment]
I'll merge and see if it goes away. Travis passes which is more important. Netlify is nice to have

**Pull request merged**
