### PR TITLE
feat: add country map of bulgaria in superset-ui-legacy-plugin-chart-country-map

### PR DESCRIPTION
**Pull request by djok**
…art-country-map

💔 Breaking Changes
NO
🏆 Enhancements
Add Bulgaria to list of countries in superset-ui-legacy-plugin-chart-country-map
📜 Documentation

🐛 Bug Fix

🏠 Internal

### CODE REVIEW

**Comment by mistercrunch** [comment]
LGTM, I'm not sure what's up with the Travis build. Seems like issues on their side.

**Comment by djok** [comment]
How can we proceed, Do I have to open an issue about Travis? Can PR be merged to the master and NPM package released?

btw, I have also [PR#6938@incubator-superset ](https://github.com/apache/incubator-superset/pull/6938) for plugin configuration.

**Comment by kristw** [comment]
Thank you for your contribution. Looks good. I am about to add a few more things to `master` and will ask you to `rebase`on top of `master` after that to see if it will help.

**Comment by djok** [comment]
@kristw For some reason, Travis FAIL again.

**Comment by kristw** [comment]
@djok I checked and the issue is not related to this PR. I will merge and take care of that.

**Comment by djok** [comment]
@kristw Any idea when NPM will be updated?

**Comment by kristw** [comment]
Can publish by end of week, but there are a few breaking changes to `@superset-ui` that need to be addressed in `incubator-superset` so cannot just bump version number immediately.

**Pull request merged**
