### PR TITLE
fix(legacy-table): when data is empty

### PR DESCRIPTION
**Pull request by ktmud**
This one is pretty straightforward.

## Test Plan

A new unit test case is added.

🐛 Bug Fix

cc: @kristw @graceguo-supercat @etr2460

### CODE REVIEW

**Review by etr2460 — APPROVED** [review]
lgtm, could you add the test plan to the PR summary though?

**Comment by ktmud** [comment]
> lgtm, could you add the test plan to the PR summary though?

I'll do that in the Superset PR.

**Comment by etr2460** [comment]
Something as simple as:

"Added a new storybook example and ensured all the examples still render properly" is fine. It's generally a good idea to include how code was tested in the PR summary so that we can refer back to it in the future

**Comment by ktmud** [comment]
Oh, I didn't add a new storybook example. Thought the unit test was enough.

**Pull request merged**
