### PR TITLE
feat: Add Iran to countries

### PR DESCRIPTION
**Pull request by ali-behjati**

### CODE REVIEW

**Comment by ali-behjati** [comment]
I can't understand why travis ci failed. Can anyone help?

**Comment by rusackas** [comment]
> I can't understand why travis ci failed. Can anyone help?

The commentlint bot is a stickler for the format of commit messages. Commit messages have to have a "conventional commit" prefix, i.e. instead of "Add Iran to countries", try "feat: Add Iran to countries". You'll have to amend your commit and force push on your fork to do this.

**Comment by ali-behjati** [comment]
I changed commits. I don't know why travis CI didn't work. It looks irrelevant.

**Comment by rusackas** [comment]
> I changed commits. I don't know why travis CI didn't work. It looks irrelevant.

Your commit went further this time, making it through the Semantic Pull Request and commitlint steps, so that's good! Now you're indeed blocked by Travis issues, that seem to be blocking all PRs on the repo.

**Review by kristw — APPROVED** [review]

**Pull request merged**
