### PR TITLE
feat: add Korea(South) to Country Maps

### PR DESCRIPTION
**Pull request by yahwang**
🏆 Enhancements - adding Korea(South) onto the ui plugins options.

screenshot

### CODE REVIEW

**Comment by kristw** [comment]
Please rebase

**Comment by yahwang** [comment]
> Please rebase

@kristw I rebased. Is there anything wrong in my request?

**Comment by kristw** [comment]
@yahwang Thank you for rebasing. I was on vacation. Code looks good but have you tested it at all? If so, it would be good to add some notes.

**Comment by yahwang** [comment]
@kristw I tested on 0.28.1 version because I don't know well about new version. 
It seems OK to visualize my data. 

korea_country_map

test data : https://gist.github.com/yahwang/25b5606d8f07bc1d85596d633f40cbf7

**Review by kristw — APPROVED** [review]

**Pull request merged**
